// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9pntICZWW3wijc-KahRNd81AdIRUeHWk',
    appId: '1:452159852960:web:9fd8dc7fcbcaaf08b9d4c5',
    messagingSenderId: '452159852960',
    projectId: 'notes-dart',
    authDomain: 'notes-dart.firebaseapp.com',
    storageBucket: 'notes-dart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbQNJGjAsZIgCIgDnf3ChXgDtotfoWUhc',
    appId: '1:452159852960:android:86427c0e5200c2d7b9d4c5',
    messagingSenderId: '452159852960',
    projectId: 'notes-dart',
    storageBucket: 'notes-dart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQkyGFC0JZ0nON437SXEGETNs1cbDAhXI',
    appId: '1:452159852960:ios:3e89a317134c2440b9d4c5',
    messagingSenderId: '452159852960',
    projectId: 'notes-dart',
    storageBucket: 'notes-dart.appspot.com',
    iosClientId: '452159852960-ius2hk1l5vnecl0nnig2daee3f7n76up.apps.googleusercontent.com',
    iosBundleId: 'work.ashraf.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQkyGFC0JZ0nON437SXEGETNs1cbDAhXI',
    appId: '1:452159852960:ios:3e89a317134c2440b9d4c5',
    messagingSenderId: '452159852960',
    projectId: 'notes-dart',
    storageBucket: 'notes-dart.appspot.com',
    iosClientId: '452159852960-ius2hk1l5vnecl0nnig2daee3f7n76up.apps.googleusercontent.com',
    iosBundleId: 'work.ashraf.notes',
  );
}
